CPPPATH = [
    '/home/rykomats/sandbox/v8/include',
    '/opt/clearsilver-0.10.5/include/ClearSilver'
]

LIBPATH = [
    '/opt/lib',
    '/opt/clearsilver-0.10.5/lib'
]

LIBS = [
    'v8',
    'neo_cs',
    'neo_utl',
    'stdc++'
]

env = Environment(CPPPATH=CPPPATH, LIBPATH=LIBPATH, LIBS=LIBS, SHLIBPREFIX='')
env.SharedLibrary('clearsilver', ['clearsilver.cc'])
