CPPPATH = [
    '/Users/rykomats/sandbox/v8/include',
]

LIBPATH = [
    '/Users/rykomats/sandbox/v8',
]

LIBS = [
    'v8',
    'stdc++'
]

env = Environment(CCFLAGS='-arch x86_64 -m64 -Wall -O2', CPPPATH=CPPPATH, LIBPATH=LIBPATH, LIBS=LIBS, SHLIBPREFIX='')
env.SharedLibrary('uuid', ['uuid.cc'])
