CPPPATH = [
    '/Users/rykomats/sandbox/v8/include',
]

LIBPATH = [
    '/Users/rykomats/sandbox/v8',
    '/usr/lib',
]

LIBS = [
    'v8',
    #'ssl',
    'crypto',
    'stdc++'
]

env = Environment(CCFLAGS='-arch x86_64 -m64', CPPPATH=CPPPATH, LIBPATH=LIBPATH, LIBS=LIBS, SHLIBPREFIX='')
env.SharedLibrary('hmac', ['hmac.cc'])
