CPPPATH = [
    '/home/rykomats/sandbox/v8/include',
    '/home/rykomats/build/tokyocabinet/include'
]

LIBPATH = [
    '/home/rykomats/sandbox/v8',
    '/home/rykomats/build/tokyocabinet/lib'
]

LIBS = [
    'v8',
    'tokyocabinet',
    'stdc++'
]

env = Environment(CPPPATH=CPPPATH, LIBPATH=LIBPATH, LIBS=LIBS, SHLIBPREFIX='')
env.SharedLibrary('tchdb', ['tchdb.cc'])
