CPPPATH = [
    '/Users/rykomats/sandbox/v8/include',
    '/Users/rykomats/build/tokyocabinet/include',
]

LIBPATH = [
    '/home/rykomats/sandbox/v8',
    '/home/rykomats/build/tokyocabinet/lib'
]

LIBS = [
    'v8',
    'tokyocabinet',
    'stdc++'
]

env = Environment(CCFLAGS='-arch x86_64 -m64', CPPPATH=CPPPATH, LIBPATH=LIBPATH, LIBS=LIBS, SHLIBPREFIX='')
env.SharedLibrary('tokyo', ['tokyo.cc'])
